# Generated by Django 5.0.2 on 2024-06-14 18:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import hermandabd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0014_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hermandad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('poblacion', models.CharField(max_length=100)),
                ('cif', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('hermandad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermandabd.hermandad')),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('hermandad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermandabd.hermandad')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to=hermandabd.models.PathAndRename('documentos'))),
                ('mime_type', models.CharField(max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('etiquetas', models.ManyToManyField(blank=True, related_name='documentos', to='hermandabd.etiqueta')),
                ('hermandad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermandabd.hermandad')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(blank=True, choices=[('GS', 'Gestor'), ('SE', 'Secretario'), ('MA', 'Mayordomo')], max_length=2, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('hermandad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hermandabd.hermandad')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Hermano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=9)),
                ('codigo_postal', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(53000)])),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_alta', models.DateField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('forma_pago', models.CharField(max_length=50)),
                ('iban', models.CharField(max_length=24)),
                ('localidad', models.CharField(max_length=50)),
                ('numero_hermano', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999)])),
                ('provincia', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=12)),
                ('titular_cuenta_bancaria', models.CharField(max_length=150)),
                ('tutor_legal', models.CharField(blank=True, max_length=150, null=True)),
                ('hermandad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermandabd.hermandad')),
            ],
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=100)),
                ('cuerpo', models.CharField(max_length=1000)),
                ('fecha_envio', models.DateField()),
                ('hermandad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermandabd.hermandad')),
                ('destinatarios', models.ManyToManyField(to='hermandabd.hermano')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('ubicacion', models.CharField(max_length=200)),
                ('hermandad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermandabd.hermandad')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hermandad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermandabd.hermandad')),
                ('hermano', models.ManyToManyField(to='hermandabd.hermano')),
            ],
        ),
        migrations.CreateModel(
            name='PapeletaSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('puesto', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('hermandad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermandabd.hermandad')),
                ('hermano', models.ManyToManyField(to='hermandabd.hermano')),
            ],
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha_llegada', models.DateField()),
                ('fecha_realizacion', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hermandad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hermandabd.hermandad')),
            ],
        ),
    ]
