# Generated by Django 5.0.2 on 2024-06-03 19:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermandabd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='papeletasitio',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='papeletasitio',
            name='puesto',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hermano',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='tutor_legal',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
