# Generated by Django 5.0.2 on 2024-06-15 19:56

import hermandabd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermandabd', '0002_pago_diseno'),
    ]

    operations = [
        migrations.AddField(
            model_name='papeletasitio',
            name='diseno',
            field=models.FileField(null=True, upload_to=hermandabd.models.PathAndRename('documentos')),
        ),
    ]
