# Generated by Django 5.0.2 on 2024-06-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermandabd', '0002_papeletasitio_hora_papeletasitio_puesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='destinatarios',
            field=models.ManyToManyField(to='hermandabd.hermano'),
        ),
    ]
