# Generated by Django 5.0.2 on 2024-06-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermandabd', '0003_carta_destinatarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='Hermandad',
            new_name='hermandad',
        ),
        migrations.RenameField(
            model_name='etiqueta',
            old_name='Hermandad',
            new_name='hermandad',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='ruta',
        ),
        migrations.AddField(
            model_name='documento',
            name='archivo',
            field=models.FileField(default='', upload_to='documentos/'),
            preserve_default=False,
        ),
    ]
