# Generated by Django 5.0.2 on 2024-06-12 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermandabd', '0004_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hermano',
            name='numero_hermano',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterUniqueTogether(
            name='hermano',
            unique_together={('hermandad', 'numero_hermano')},
        ),
    ]
