# Generated by Django 5.0.2 on 2024-06-05 10:56

import django.utils.timezone
import hermandabd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermandabd', '0004_rename_hermandad_documento_hermandad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to=hermandabd.models.PathAndRename('documentos')),
        ),
        migrations.AlterField(
            model_name='documento',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, to='hermandabd.etiqueta'),
        ),
    ]
