# Generated by Django 5.0.2 on 2024-06-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hermandabd', '0005_alter_hermano_numero_hermano_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hermano',
            unique_together=set(),
        ),
    ]
