# Generated by Django 5.0.2 on 2024-06-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermandabd', '0006_alter_hermano_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='mime_type',
            field=models.CharField(default='pdf', max_length=20),
            preserve_default=False,
        ),
    ]
