# Generated by Django 5.0.2 on 2024-06-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermandabd', '0007_documento_mime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiqueta',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='documento',
            name='mime_type',
            field=models.CharField(max_length=100),
        ),
    ]
